workflows:
  ios_build:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
