workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.erestreaming.ere"   # YOUR ANDROID PACKAGE NAME
        GOOGLE_PLAY_TRACK: "alpha"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Flutter analyze
        script: flutter analyze

      - name: Flutter unit tests
        script: flutter test
        ignore_failure: true

      - name: Build Android AAB
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/**/outputs/**/*.aab
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true


  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: codemagic   # Uses your API key

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.erestreaming.ere   # <-- YOUR OFFICIAL BUNDLE ID

      vars:
        APP_ID: 6755789905   # <-- YOUR REAL APP STORE APP ID

      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up code signing profiles
        script: xcode-project use-profiles

      - name: Install Flutter packages
        script: flutter packages pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Analyze Flutter code
        script: flutter analyze

      - name: Flutter tests
        script: flutter test
        ignore_failure: true

      - name: Build iOS IPA with automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number --platform=IOS "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com
        notify:
          success: true
          failure: false

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Public Testers

  web-workflow:
    name: Web app workflow
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Flutter analyze
        script: flutter analyze

      - name: Flutter unit tests
        script: flutter test

      - name: Build Flutter Web
        script: |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*

    artifacts:
      - build/web.zip
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com
